### PR TITLE
css and next 13 configured

### PR DESCRIPTION
**Pull request by izakrobles**
Completed Issue regarding initial next.js and tailwind configuration

### CODE REVIEW

**Comment by izakrobles** [comment]
The initial work on this issue was pushed directly to main by accident because of muscle memory. Made a slight modification to move the changes into the draft PR

**Comment by kate-holdener** [comment]
There are changes to files that are auto-generated. We really don't want to keep different versions of auto-generated files. 

The problem with having auto-generated files in the repo is tracked under a different issue: https://github.com/oss-slu/lrda_website/issues/10

**Review by Josh-Hogan-87 — APPROVED** [review]
Looks good. Good job cleaning up your files.

**Review by yashb196 — APPROVED** [review]
Thank you for resolving that issue i am approving the PR

**Pull request merged**
