### PR TITLE
16 jest test cases rendering components

### PR DESCRIPTION
**Pull request by yashb196**
Added few basic test cases which should be helpful for you guys to understand how the test cases are written 

all the basic test cases are here 

3 important key notes 

1. understand how the test case is written (format) 
2. see what were the criteria's mentioned for them to pass 
3. understand how to use **Moxios and Stubs** to generate fake requests

### CODE REVIEW

**Review by izakrobles — APPROVED** [review]
This looks good Yash! I think I learned a lot about writing test cases. Thank you for keeping the detailed comments.

**Comment by Stuartwastaken** [comment]
Great job writing these. It gives us a good idea of how to structure test cases going forward with our components. Made great use of utilizing the utils files.

**Review by Stuartwastaken — APPROVED** [review]
Great job writing these. It gives us a good idea of how to structure test cases going forward with our components. Made great use of utilizing the utils files.

**Review by Josh-Hogan-87 — APPROVED** [review]
Thank you for writing these test cases Yash. This should go a long way in our understanding when we have to write test cases of our own for this project.

**Pull request merged**
