### PR TITLE
Inital search and logic

### PR DESCRIPTION
**Pull request by Josh-Hogan-87**
This draft is just an example of what the search bar and logic could be. I need to get with the team so they can further explain what the code is doing and how to run the code in order to create the needed code to solve this issue. A data structure will also need to be discussed.

### CODE REVIEW

**Comment by izakrobles** [comment]
Looks like a good starting point with the file names, but ui still needs to be built out

**Comment by Stuartwastaken** [comment]
Good job thanks for removing the binary files. The search bar looks like it could use some styling but overall is exactly what this issue entails. I'll go ahead and merge this to main.

**Comment by Stuartwastaken** [comment]
This resolves this issue: https://github.com/oss-slu/lrda_website/issues/5. Everything seems to be fine and we will add functionality later by importing that from LRDA_Mobile.

**Review by Stuartwastaken — APPROVED** [review]
This resolves this issue: https://github.com/oss-slu/lrda_website/issues/5. Everything seems to be fine and we will add functionality later by importing that from LRDA_Mobile.

**Review by yashb196 — APPROVED** [review]
looks good approving the request please do follow @Stuartwastaken's Advice

**Pull request merged**
